/**
 * Routes mounted after verifyToken (JWT cookie auth).
 */
import profileRoutes from "../portals/admin/routes/profileRoutes.js";
import dashboardRoutes from "../portals/admin/routes/dashboardRoutes.js";
import employeeRoutes from "../portals/admin/routes/employeeRoutes.js";
import builderRoutes from "../portals/admin/routes/builderRoutes.js";
import propertyRoutes from "../portals/admin/routes/propertyRoutes.js";
import propertyAdditionalInfoRoutes from "../portals/admin/routes/propertyAdditionalInfoRoutes.js";
import customerRoutes from "../portals/admin/routes/customerRoutes.js";
import roleRoutes from "../portals/admin/routes/roleRoutes.js";
import departmentRoutes from "../portals/admin/routes/departmentRoutes.js";
import authoritiesRoutes from "../portals/admin/routes/authoritiesRoutes.js";
import stateRoutes from "../portals/admin/routes/stateRoutes.js";
import cityRoutes from "../portals/admin/routes/cityRoutes.js";
import mapRoutes from "../portals/admin/routes/mapRoutes.js";
import promoterRoutes from "../portals/admin/routes/promoterRoutes.js";
import adsManagerRoutes from "../portals/admin/routes/adsManagerRoutes.js";
import salespersonRoutes from "../portals/admin/routes/salespersonRoutes.js";
import partnerRoutes from "../portals/admin/routes/partnerRoutes.js";
import projectPartnerRoutes from "../portals/admin/routes/projectPartnerRoutes.js";
import territoryPartnerRoutes from "../portals/admin/routes/territoryPartnerRoutes.js";
import guestUserRoutes from "../portals/admin/routes/guestUserRoutes.js";
import subscriptionPricingRoutes from "../portals/admin/routes/subscriptionPricingRoutes.js";
import subscriptionDiscountRoutes from "../portals/admin/routes/subscriptionDiscountRoutes.js";
import propertytypeRoutes from "../portals/admin/routes/propertytypeRoutes.js";
import enquirerRoutes from "../portals/admin/routes/enquirerRoutes.js";
import callEnquirerRoutes from "../portals/admin/routes/callEnquirerRoutes.js";
import whatsappEnquirerRoutes from "../portals/admin/routes/whatsappEnquirerRoutes.js";
import addEnquiryRoutes from "../portals/admin/routes/enquiryRoutes.js";
import auctionmembersRoutes from "../portals/admin/routes/auctionmemberRoutes.js";
import ticketRoutes from "../portals/admin/routes/ticketRoutes.js";
import apkUploadRoutes from "../portals/admin/routes/apkUploadRoutes.js";
import blogRoutes from "../portals/admin/routes/blogRoutes.js";
import trendRoutes from "../portals/admin/routes/trendRoutes.js";
import sliderRoutes from "../portals/admin/routes/sliderRoutes.js";
import testimonialRoutes from "../portals/admin/routes/testimonialRoutes.js";
import calenderRoutes from "../portals/admin/routes/calenderRoutes.js";
import emiRoutes from "../portals/admin/routes/emiRoutes.js";
import marketingContentRoutes from "../portals/admin/routes/marketingContentRoutes.js";
import brandAccessoriesRoutes from "../portals/admin/routes/brandAccessoriesRoutes.js";
import messageRoutes from "../portals/admin/routes/messageRoutes.js";
import contactUsRoutes from "../portals/admin/routes/contactUsRoutes.js";
import scheduledRequestRoutes from "../portals/admin/routes/scheduledRequestRoutes.js";
import FAQRoutes from "../portals/admin/routes/FAQRoutes.js";
import propertyAnalyticsRoutes from "../portals/admin/routes/propertyAnalyticsRoutes.js";
import blogAnalyticsRoutes from "../portals/admin/routes/blogAnalyticsRoutes.js";
import newsRoutes from "../portals/admin/routes/newsRoute.js";
import newsAnalyticsRoutes from "../portals/admin/routes/newsAnalyticsRoutes.js";
import subscribersRoutes from "../portals/admin/routes/subscribersRoutes.js";
import whatsappChatRoutes from "../portals/admin/routes/whatsappChatRoutes.js";

import guestUserLoginRoutes from "../portals/guestUser/routes/userRoutes.js";
import guestUserProfileRoutes from "../portals/guestUser/routes/profileRoutes.js";
import guestUserDashboardRoutes from "../portals/guestUser/routes/dashboardRoutes.js";
import guestUserPropertyRoutes from "../portals/guestUser/routes/propertyRoutes.js";
import guestUserMapRoutes from "../portals/guestUser/routes/mapRoutes.js";
import guestUserBuilderRoutes from "../portals/guestUser/routes/builderRoutes.js";

import userLoginRoutes from "../portals/user/routes/userRoutes.js";
import userProfileRoutes from "../portals/user/routes/profileRoutes.js";
import userDashboardRoutes from "../portals/user/routes/dashboardRoutes.js";
import userPropertyRoutes from "../portals/user/routes/propertyRoutes.js";
import userEnquirersRoutes from "../portals/user/routes/enquirerRoutes.js";
import userMapRoutes from "../portals/user/routes/mapRoutes.js";
import userBuilderRoutes from "../portals/user/routes/builderRoutes.js";
import userAuthRoutes from "../portals/user/routes/authRoutes.js";
import userEmiRoutes from "../portals/user/routes/emiRoutes.js";
import userActivityRoutes from "../portals/user/routes/activityRoutes.js";

import builderLoginRoutes from "../portals/builder/routes/loginRoutes.js";
import builderProfileRoutes from "../portals/builder/routes/profileRoutes.js";
import builderDashboardRoutes from "../portals/builder/routes/dashboardRoutes.js";
import builderCustomerRoutes from "../portals/builder/routes/customerRoutes.js";
import builderPropertyRoutes from "../portals/builder/routes/propertyRoutes.js";
import builderTicketRoutes from "../portals/builder/routes/ticketRoutes.js";

import employeeLoginRoutes from "../portals/employee/routes/employeeLoginRoutes.js";
import employeeProfileRoutes from "../portals/employee/routes/employeeProfileRoutes.js";
import employeeDashboardRoutes from "../portals/employee/routes/dashboardRoutes.js";
import employeeTicketRoutes from "../portals/employee/routes/employeeTicketRoutes.js";
import employeeBuilderRoutes from "../portals/employee/routes/builderRoutes.js";
import employeePropertyRoutes from "../portals/employee/routes/propertyRoutes.js";
import employeeEnquirersRoutes from "../portals/employee/routes/enquirerRoutes.js";
import employeeEnquiryRoutes from "../portals/employee/routes/enquiryRoutes.js";
import employeeCustomerRoutes from "../portals/employee/routes/customerRoutes.js";
import employeeSalesPartnerRoutes from "../portals/employee/routes/salesPartnerRoutes.js";
import employeeTerritoryPartnerRoutes from "../portals/employee/routes/territoryPartnerRoutes.js";
import employeeMapRoutes from "../portals/employee/routes/mapRoutes.js";
import employeeCalenderRoutes from "../portals/employee/routes/calenderRoutes.js";
import employeeRoleRoutes from "../portals/employee/routes/roleRoutes.js";
import employeeDepartmentRoutes from "../portals/employee/routes/departmentRoutes.js";
import employeeMessageRoutes from "../portals/employee/routes/messageRoutes.js";

import promoterLoginRoutes from "../portals/promoter/routes/loginRoutes.js";
import promoterProfileRoutes from "../portals/promoter/routes/profileRoutes.js";
import promoterAgreementRoutes from "../portals/promoter/routes/agreementRoutes.js";
import promoterDashboardRoutes from "../portals/promoter/routes/dashboardRoutes.js";
import promoterEnquirerRoutes from "../portals/promoter/routes/enquirerRoutes.js";
import promoterCustomerRoutes from "../portals/promoter/routes/customerRoutes.js";
import promoterSalespersonRoutes from "../portals/promoter/routes/salespersonRoutes.js";
import promoterPartnerRoutes from "../portals/promoter/routes/partnerRoutes.js";
import promoterProjectPartnerRoutes from "../portals/promoter/routes/projectPartnerRoutes.js";
import promoterTerritoryPartnerRoutes from "../portals/promoter/routes/territoryPartnerRoutes.js";
import promoterEmiRoutes from "../portals/promoter/routes/emiRoutes.js";
import promoterTicketRoutes from "../portals/promoter/routes/ticketRoutes.js";

import salesLoginRoutes from "../portals/sales/routes/salesLoginRoutes.js";
import salesProfileRoutes from "../portals/sales/routes/salesProfileRoutes.js";
import salesAgreementRoutes from "../portals/sales/routes/agreementRoutes.js";
import salesDashboardRoutes from "../portals/sales/routes/dashboardRoutes.js";
import salesPropertyRoutes from "../portals/sales/routes/salesPropertyRoutes.js";
import salesTicketRoutes from "../portals/sales/routes/salesTicketRoutes.js";
import salesCustomerRoutes from "../portals/sales/routes/customerRoutes.js";
import salesEnquirersRoutes from "../portals/sales/routes/salesEnquirerRoutes.js";
import salesEnquiryRoutes from "../portals/sales/routes/salesEnquiryRoutes.js";
import salesCalenderRoutes from "../portals/sales/routes/calenderRoutes.js";
import salesPropertiesRoutes from "../portals/sales/routes/propertiesRoutes.js";
import salesPropertyinfoRoutes from "../portals/sales/routes/propertyinfoRoutes.js";
import enquiryRoutesSaleApp from "../portals/salesApp/routes/enquiryRoute.js";
import salesSubscriptionRoutes from "../portals/sales/routes/subscriptionRoutes.js";

import partnerLoginRoutes from "../portals/onboardingPartner/routes/partnerLoginRoutes.js";
import partnerProfileRoutes from "../portals/onboardingPartner/routes/partnerProfileRoutes.js";
import partnerAgreementRoutes from "../portals/onboardingPartner/routes/agreementRoutes.js";
import partnerDashboardRoutes from "../portals/onboardingPartner/routes/dashboardRoutes.js";
import partnerPropertyRoutes from "../portals/onboardingPartner/routes/partnerPropertyRoutes.js";
import partnerMapRoutes from "../portals/onboardingPartner/routes/mapRoutes.js";
import partnerBuilderRoutes from "../portals/onboardingPartner/routes/partnerBuilderRoutes.js";
import partnerTicketRoutes from "../portals/onboardingPartner/routes/partnerTicketRoutes.js";

import projectPartnerLoginRoutes from "../portals/projectPartner/routes/loginRoutes.js";
import projectPartnerProfileRoutes from "../portals/projectPartner/routes/profileRoutes.js";
import projectPartnerAgreementRoutes from "../portals/projectPartner/routes/agreementRoutes.js";
import projectPartnerDashboardRoutes from "../portals/projectPartner/routes/dashboardRoutes.js";
import projectPartnerPropertyRoutes from "../portals/projectPartner/routes/propertyRoutes.js";
import projectPartnerPropertyAdditionalInfoRoutes from "../portals/projectPartner/routes/propertyAdditionalInfoRoutes.js";
import projectPartnerMapRoutes from "../portals/projectPartner/routes/mapRoutes.js";
import projectPartnerCustomerRoutes from "../portals/projectPartner/routes/customerRoutes.js";
import projectPartnerBuilderRoutes from "../portals/projectPartner/routes/builderRoutes.js";
import projectPartnerTicketRoutes from "../portals/projectPartner/routes/ticketRoutes.js";
import projectSalesPartnerRoutes from "../portals/projectPartner/routes/salesPartnerRoutes.js";
import projectTerritoryPartnerRoutes from "../portals/projectPartner/routes/territoryPartnerRoutes.js";
import projectEnquirerRoutes from "../portals/projectPartner/routes/enquirerRoutes.js";
import projectEnquiryRoutes from "../portals/projectPartner/routes/enquiryRoutes.js";
import projectCalenderRoutes from "../portals/projectPartner/routes/calenderRoutes.js";
import projectEmployeeRoutes from "../portals/projectPartner/routes/employeeRoutes.js";
import projectRoleRoutes from "../portals/projectPartner/routes/roleRoutes.js";
import projectDepartmentRoutes from "../portals/projectPartner/routes/departmentRoutes.js";
import projectSliderRoutes from "../portals/projectPartner/routes/sliderRoutes.js";
import projectPartnerMessageRoutes from "../portals/projectPartner/routes/messageRoutes.js";
import projectPartnerSubscriptionRoutes from "../portals/projectPartner/routes/subscriptionRoutes.js";
import projectPartnerSalesAndTerritoryRoutes from "../portals/projectPartner/routes/partnerRoutes.js";
import projectPartnerEventRoutes from "../portals/projectPartner/routes/eventRoutes.js";

import territoryPartnerLoginRoutes from "../portals/territoryPartner/routes/loginRoutes.js";
import territoryPartnerProfileRoutes from "../portals/territoryPartner/routes/profileRoutes.js";
import territoryPartnerAgreementRoutes from "../portals/territoryPartner/routes/agreementRoutes.js";
import territoryPartnerDashboardRoutes from "../portals/territoryPartner/routes/dashboardRoutes.js";
import territoryPartnerBuilderRoutes from "../portals/territoryPartner/routes/builderRoutes.js";
import territoryPartnerTicketRoutes from "../portals/territoryPartner/routes/ticketRoutes.js";
import territoryPartnerCustomerRoutes from "../portals/territoryPartner/routes/customerRoutes.js";
import territoryPartnerEnquirersRoutes from "../portals/territoryPartner/routes/enquirerRoutes.js";
import territoryPartnerEnquiryRoutes from "../portals/territoryPartner/routes/enquiryRoutes.js";
import territoryPartnerCalenderRoutes from "../portals/territoryPartner/routes/calenderRoutes.js";
import territoryPartnerPropertiesRoutes from "../portals/territoryPartner/routes/propertiesRoutes.js";
import territoryPartnerPropertyinfoRoutes from "../portals/territoryPartner/routes/propertyinfoRoutes.js";
import territoryPartnerSubscriptionRoutes from "../portals/territoryPartner/routes/subscriptionRoutes.js";

import bookPropertyRoute from "../portals/sales/routes/propertyBookingRoute.js";
import authRoute from "../portals/salesApp/routes/authRoute.js";
import appFlatRoute from "../portals/salesApp/routes/flatRoutes.js";
import appTicketRoute from "../portals/salesApp/routes/ticketRoute.js";
import postRoute from "../portals/salesApp/routes/postRoutes.js";
import userController from "../portals/salesApp/routes/userRoute.js";
import clientRoute from "../portals/salesApp/routes/clientRoute.js";
import salesPropertyEnquiry from "../portals/salesApp/routes/propertyEnquiry.js";
import territoryUserController from "../portals/territoryApp/routes/userRoute.js";
import territorypostRoute from "../portals/territoryApp/routes/postRoutes.js";
import territoryBooking from "../portals/territoryPartner/routes/propertyBookingRoute.js";
import territoryClientRoute from "../portals/territoryApp/routes/profileRoute.js";
import territoryEnquiryRoute from "../portals/territoryApp/routes/enquiryRoute.js";
import territoryPropertyEnquiryRoute from "../portals/territoryApp/routes/propertyEnquiriesRoute.js";
import territorySubscription from "../portals/territoryApp/routes/subscription.js";
import territoryAuth from "../portals/territoryApp/routes/authRoutes.js";
import salesSubscription from "../portals/salesApp/routes/subscription.js";
import scheduleNotesRoutes from "../portals/salesApp/routes/notesRoute.js";
import onboardingAppRoute from "../portals/onboardingApp/routes/userRoute.js";
import onboardingPartnerPostRoute from "../portals/onboardingApp/routes/postRoutes.js";
import onboardingSubscription from "../portals/onboardingApp/routes/subscription.js";
import projectPartnerAppRoute from "../portals/projectPartnerApp/routes/userRoute.js";
import projectPartnerPostRoute from "../portals/projectPartnerApp/routes/postRoutes.js";
import projectSubscription from "../portals/projectPartnerApp/routes/subscription.js";
import projectEnquiriesRoute from "../portals/projectPartnerApp/routes/enquiryRoute.js";
import projectpartnerSalesAndTerritoryRoute from "../portals/projectPartnerApp/routes/partnerRoute.js";
import projectPartnerEmployee from "../portals/projectPartnerApp/routes/employeeRoute.js";
import projectPartnerTickets from "../portals/projectPartnerApp/routes/ticketRouter.js";
import projectpartnerappDepartment from "../portals/projectPartnerApp/routes/departmentRoutes.js";
import projectPartnerRoles from "../portals/projectPartnerApp/routes/roleRoutes.js";
import projectPartnerAppPropertyRoute from "../portals/projectPartnerApp/routes/propertyRoute.js";
import projectPartnerAppBuilderRoute from "../portals/projectPartnerApp/routes/builderRoutes.js";
import projectPartnerAppAuth from "../portals/projectPartnerApp/routes/authRoutes.js";
import projectPartnerEvent from "../portals/projectPartnerApp/routes/eventRoutes.js";
import projectPartnerProfile from "../portals/projectPartnerApp/routes/profileRoute.js";

import customerEmi from "../portals/customerApp/routes/EmiRoute.js";
import customerSignUp from "../portals/customerApp/routes/userRoute.js";
import customerPropertyRoute from "../portals/customerApp/routes/propertyRoute.js";
import customerTrendRoute from "../portals/customerApp/routes/trendRoute.js";
import customerEnquiryRoute from "../portals/customerApp/routes/enquiryRoute.js";
import customerTicketRoute from "../portals/customerApp/routes/ticketRoute.js";
import notificationRoutes from "../portals/customerApp/routes/notificationRoutes.js";
import customerNotifyRoute from "../portals/customerApp/routes/notifyroute.js";

import builderapploginRoute from "../portals/builderApp/routes/builderapploginRoute.js";
import builderProfileRoute from "../portals/builderApp/routes/builderProfileRoutes.js";
import builderpropertyRoute from "../portals/builderApp/routes/propertyController.js";
import builderEnquiryCustomerRoute from "../portals/builderApp/routes/builderPropertyEnquiryRoute.js";
import builderCommunityRoute from "../portals/builderApp/routes/communityRoute.js";
import builderTicketRoute from "../portals/builderApp/routes/BuilderTicketRoutes.js";
import builderpostRoute from "../portals/builderApp/routes/BuilderpostRoutes.js";

import userRoutes from "../portals/event/routes/authRoute.js";
import eventuserProfileRoutes from "../portals/event/routes/profileRoute.js";
import eventHandlerRoutes from "../portals/event/routes/eventRoute.js";
import eventBookingRoutes from "../portals/event/routes/bookingRoute.js";

import { verifyToken } from "../core/middleware/verifyToken.js";

export function mountProtectedRoutes(app) {
  app.use("/admin/profile", profileRoutes);
  app.use("/admin/dashboard", dashboardRoutes);
  app.use("/admin/employees", employeeRoutes);
  app.use("/admin/properties", propertyRoutes);
  app.use("/admin/property/additional-info", propertyAdditionalInfoRoutes);
  app.use("/admin/builders", builderRoutes);
  app.use("/admin/customers", customerRoutes);
  app.use("/admin/roles", roleRoutes);
  app.use("/admin/departments", departmentRoutes);
  app.use("/admin/authorities", authoritiesRoutes);
  app.use("/admin/states", stateRoutes);
  app.use("/admin/cities", cityRoutes);
  app.use("/admin/map", mapRoutes);
  app.use("/admin/promoter", promoterRoutes);
  app.use("/admin/ads-manager", adsManagerRoutes);
  app.use("/admin/salespersons", salespersonRoutes);
  app.use("/admin/partner", partnerRoutes);
  app.use("/admin/projectpartner", projectPartnerRoutes);
  app.use("/admin/territorypartner", territoryPartnerRoutes);
  app.use("/admin/guestuser", guestUserRoutes);
  app.use("/admin/subscription/pricing", subscriptionPricingRoutes);
  app.use("/admin/subscription/discount", subscriptionDiscountRoutes);
  app.use("/admin/propertytypes", propertytypeRoutes);
  app.use("/admin/enquirers", enquirerRoutes);
  app.use("/admin/call-enquirers", callEnquirerRoutes);
  app.use("/admin/whatsapp-enquirers", whatsappEnquirerRoutes);
  app.use("/admin/whatsapp-chat", whatsappChatRoutes);
  app.use("/admin/enquiries", verifyToken, addEnquiryRoutes);
  app.use("/admin/auctionmembers", auctionmembersRoutes);
  app.use("/admin/tickets", ticketRoutes);
  app.use("/admin/apk", apkUploadRoutes);
  app.use("/admin/blog", blogRoutes);
  app.use("/admin/trend", trendRoutes);
  app.use("/admin/slider", sliderRoutes);
  app.use("/admin/testimonial", testimonialRoutes);
  app.use("/admin/calender", calenderRoutes);
  app.use("/admin/emi", emiRoutes);
  app.use("/admin/marketing-content", marketingContentRoutes);
  app.use("/admin/brand-accessories", brandAccessoriesRoutes);
  app.use("/admin/messages", messageRoutes);
  app.use("/admin/contact-us", contactUsRoutes);
  app.use("/admin/scheduled-requests", scheduledRequestRoutes);
  app.use("/admin/faqs", FAQRoutes);
  app.use("/admin/propertyAnalytics", propertyAnalyticsRoutes);
  app.use("/admin/blogAnalytics", blogAnalyticsRoutes);
  app.use("/admin/news", newsRoutes);
  app.use("/admin/newsAnalytics", newsAnalyticsRoutes);
  app.use("/admin/subscribers", subscribersRoutes);

  app.use("/guest-user", guestUserLoginRoutes);
  app.use("/guest-user/profile", guestUserProfileRoutes);
  app.use("/guest-user/dashboard", guestUserDashboardRoutes);
  app.use("/guest-user/builders", guestUserBuilderRoutes);
  app.use("/guest-user/properties", guestUserPropertyRoutes);
  app.use("/guest-user/map", guestUserMapRoutes);

  app.use("/user", userLoginRoutes);
  app.use("/user/profile", userProfileRoutes);
  app.use("/user/dashboard", userDashboardRoutes);
  app.use("/user/builders", userBuilderRoutes);
  app.use("/user/properties", userPropertyRoutes);
  app.use("/user/enquirers", userEnquirersRoutes);
  app.use("/user/map", userMapRoutes);
  app.use("/user/auth", userAuthRoutes);
  app.use("/user/emi", userEmiRoutes);
  app.use("/user/activity", userActivityRoutes);

  app.use("/builder", builderLoginRoutes);
  app.use("/builder/profile", builderProfileRoutes);
  app.use("/builder/dashboard", builderDashboardRoutes);
  app.use("/builder/customers", builderCustomerRoutes);
  app.use("/builder/properties", builderPropertyRoutes);
  app.use("/builder/tickets", builderTicketRoutes);

  app.use("/employee", employeeLoginRoutes);
  app.use("/employee/profile", employeeProfileRoutes);
  app.use("/employee/dashboard", employeeDashboardRoutes);
  app.use("/employee/tickets", employeeTicketRoutes);
  app.use("/employee/builders", employeeBuilderRoutes);
  app.use("/employee/properties", employeePropertyRoutes);
  app.use("/employee/enquirers", employeeEnquirersRoutes);
  app.use("/employee/map", employeeMapRoutes);
  app.use("/employee/customers", employeeCustomerRoutes);
  app.use("/employee/sales", employeeSalesPartnerRoutes);
  app.use("/employee/territory", employeeTerritoryPartnerRoutes);
  app.use("/employee/enquiry", employeeEnquiryRoutes);
  app.use("/employee/calender", employeeCalenderRoutes);
  app.use("/employee/roles", employeeRoleRoutes);
  app.use("/employee/departments", employeeDepartmentRoutes);
  app.use("/employee/messages", employeeMessageRoutes);

  app.use("/promoter", promoterLoginRoutes);
  app.use("/promoter/profile", promoterProfileRoutes);
  app.use("/promoter/agreement", promoterAgreementRoutes);
  app.use("/promoter/dashboard", promoterDashboardRoutes);
  app.use("/promoter/enquirers", promoterEnquirerRoutes);
  app.use("/promoter/customers", promoterCustomerRoutes);
  app.use("/promoter/salespersons", promoterSalespersonRoutes);
  app.use("/promoter/partner", promoterPartnerRoutes);
  app.use("/promoter/projectpartner", promoterProjectPartnerRoutes);
  app.use("/promoter/territorypartner", promoterTerritoryPartnerRoutes);
  app.use("/promoter/emi", promoterEmiRoutes);
  app.use("/promoter/tickets", promoterTicketRoutes);

  app.use("/sales", salesLoginRoutes);
  app.use("/sales/profile", salesProfileRoutes);
  app.use("/sales/agreement", salesAgreementRoutes);
  app.use("/sales/enquirers", salesEnquirersRoutes);
  app.use("/sales/dashboard", salesDashboardRoutes);
  app.use("/sales/properties", salesPropertyRoutes);
  app.use("/sales/customers", salesCustomerRoutes);
  app.use("/sales/tickets", salesTicketRoutes);
  app.use("/sales/calender", salesCalenderRoutes);
  app.use("/sales/enquiry", salesEnquiryRoutes);
  app.use("/sales/subscription", salesSubscriptionRoutes);
  app.use("/sales/properties", salesPropertiesRoutes);
  app.use("/sales/propertyinfo", salesPropertyinfoRoutes);

  app.use("/partner", partnerLoginRoutes);
  app.use("/partner/profile", partnerProfileRoutes);
  app.use("/partner/agreement", partnerAgreementRoutes);
  app.use("/partner/dashboard", partnerDashboardRoutes);
  app.use("/partner/properties", partnerPropertyRoutes);
  app.use("/partner/map", partnerMapRoutes);
  app.use("/partner/builders", partnerBuilderRoutes);
  app.use("/partner/tickets", partnerTicketRoutes);

  app.use("/project-partner", projectPartnerLoginRoutes);
  app.use("/project-partner/profile", projectPartnerProfileRoutes);
  app.use("/project-partner/agreement", projectPartnerAgreementRoutes);
  app.use("/project-partner/dashboard", projectPartnerDashboardRoutes);
  app.use("/project-partner/properties", projectPartnerPropertyRoutes);
  app.use(
    "/project-partner/property/additional-info",
    projectPartnerPropertyAdditionalInfoRoutes,
  );
  app.use("/project-partner/map", projectPartnerMapRoutes);
  app.use("/project-partner/customers", projectPartnerCustomerRoutes);
  app.use("/project-partner/builders", projectPartnerBuilderRoutes);
  app.use("/project-partner/tickets", projectPartnerTicketRoutes);
  app.use("/project-partner/sales", projectSalesPartnerRoutes);
  app.use("/project-partner/territory", projectTerritoryPartnerRoutes);
  app.use("/project-partner/enquirers", projectEnquirerRoutes);
  app.use("/project-partner/enquiry", projectEnquiryRoutes);
  app.use("/project-partner/calender", projectCalenderRoutes);
  app.use("/project-partner/roles", projectRoleRoutes);
  app.use("/project-partner/departments", projectDepartmentRoutes);
  app.use("/project-partner/employees", projectEmployeeRoutes);
  app.use("/project-partner/slider", projectSliderRoutes);
  app.use("/project-partner/messages", projectPartnerMessageRoutes);
  app.use("/project-partner/subscription", projectPartnerSubscriptionRoutes);
  app.use("/project-partner/partner", projectPartnerSalesAndTerritoryRoutes);
  app.use("/project-partner/event", projectPartnerEventRoutes);

  app.use("/territory-partner", territoryPartnerLoginRoutes);
  app.use("/territory-partner/profile", territoryPartnerProfileRoutes);
  app.use("/territory-partner/agreement", territoryPartnerAgreementRoutes);
  app.use("/territory-partner/dashboard", territoryPartnerDashboardRoutes);
  app.use("/territory-partner/builders", territoryPartnerBuilderRoutes);
  app.use("/territory-partner/tickets", territoryPartnerTicketRoutes);
  app.use("/territory-partner/customers", territoryPartnerCustomerRoutes);
  app.use("/territory-partner/enquirers", territoryPartnerEnquirersRoutes);
  app.use("/territory-partner/enquiry", territoryPartnerEnquiryRoutes);
  app.use("/territory-partner/calender", territoryPartnerCalenderRoutes);
  app.use(
    "/territory-partner/subscription",
    territoryPartnerSubscriptionRoutes,
  );
  app.use("/territory-partner/properties", territoryPartnerPropertiesRoutes);
  app.use(
    "/territory-partner/propertyinfo",
    territoryPartnerPropertyinfoRoutes,
  );

  app.use("/salesapp/api", authRoute);
  app.use("/salesapp/flats", appFlatRoute);
  app.use("/salesapp/tickets", appTicketRoute);
  app.use("/salesapp/post", postRoute);
  app.use("/salesapp/user", userController);
  app.use("/salesapp/client", clientRoute);
  app.use("/salesapp/enquiry", enquiryRoutesSaleApp);
  app.use("/salesapp/subscription", salesSubscription);
  app.use("/salesapp/property/enquiry", salesPropertyEnquiry);
  app.use("/salesapp/schedule-notes", scheduleNotesRoutes);

  app.use("/territoryapp/user", territoryUserController);
  app.use("/territoryapp/post", territorypostRoute);
  app.use("/territoryapp/client", territoryClientRoute);
  app.use("/territoryapp/enquiry", territoryEnquiryRoute);
  app.use("/territoryapp/property/enquiry", territoryPropertyEnquiryRoute);
  app.use("/territoryapp/subscription", territorySubscription);
  app.use("/territoryapp/auth", territoryAuth);
  app.use("/api/booking", bookPropertyRoute);
  app.use("/api/booking/territory", territoryBooking);

  app.use("/onboardingapp/user", onboardingAppRoute);
  app.use("/onboardingapp/post", onboardingPartnerPostRoute);
  app.use("/onboardingapp/subscription", onboardingSubscription);

  app.use("/projectpartnerRoute/user", projectPartnerAppRoute);
  app.use("/projectpartner/post", projectPartnerPostRoute);
  app.use("/projectpartner/subscription", projectSubscription);
  app.use("/projectpartner/enquiries/", projectEnquiriesRoute);
  app.use("/projectpartner/partner", projectpartnerSalesAndTerritoryRoute);
  app.use("/projectpartner/employee", projectPartnerEmployee);
  app.use("/projectpartner/ticket", projectPartnerTickets);
  app.use("/projectpartner/departments", projectpartnerappDepartment);
  app.use("/projectpartner/roles", projectPartnerRoles);
  app.use("/projectpartner/property", projectPartnerAppPropertyRoute);
  app.use("/projectpartner/builders", projectPartnerAppBuilderRoute);
  app.use("/projectpartner/auth", projectPartnerAppAuth);
  app.use("/projectpartner/event", projectPartnerEvent);
  app.use("/projectpartner/profile", projectPartnerProfile);

  app.use("/customerapp/loans", customerEmi);
  app.use("/customerapp/user", customerSignUp);
  app.use("/customerapp/property", customerPropertyRoute);
  app.use("/customerapp/customerTrendRoute", customerTrendRoute);
  app.use("/customerapp/enquiry", customerEnquiryRoute);
  app.use("/customerapp/ticket", customerTicketRoute);
  app.use("/customerapp/notifications", notificationRoutes);
  app.use("/customerapp/notify", customerNotifyRoute);

  app.use("/builderapp/user", builderapploginRoute);
  app.use("/builderapp/profile", builderProfileRoute);
  app.use("/builderapp/property", builderpropertyRoute);
  app.use("/builderapp/customer", builderEnquiryCustomerRoute);
  app.use("/builderapp/community", builderCommunityRoute);
  app.use("/builderapp/ticket", builderTicketRoute);
  app.use("/builderapp/post", builderpostRoute);

  app.use("/event/users/auth", userRoutes);
  app.use("/event/profile", eventuserProfileRoutes);
  app.use("/event", eventHandlerRoutes);
  app.use("/event/bookings", eventBookingRoutes);
}
